import random
H = random.randint(2, 5)
W = random.randint(2, 5)
K = random.randint(1, 5)
x1 = random.randint(1, H)
x2 = random.randint(1, H)
y1 = random.randint(1, W)
y2 = random.randint(1, W)
print(H, W, K)
print(x1, y1, x2, y2)
